### ISSUE TITLE
Issue while using instapusher with Ruby 2.2

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [neerajsingh0101/instapusher#6]
```
prathamesh ~/Projects/BigBinary/bbjekyll 2.2.2 (bigbinary/bbjekyll) -> rails5-application-record
$ instapusher
/Users/prathamesh/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/instapusher-0.1.9/lib/instapusher/configuration.rb:17:in `load': undefined method `load_file' for Psych:Module (NoMethodError)
    from /Users/prathamesh/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/instapusher-0.1.9/lib/instapusher/configuration.rb:49:in `method_missing'
    from /Users/prathamesh/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/instapusher-0.1.9/lib/instapusher/commands.rb:59:in `detect_api_key'
    from /Users/prathamesh/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/instapusher-0.1.9/lib/instapusher/commands.rb:17:in `initialize'
    from /Users/prathamesh/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/instapusher-0.1.9/bin/instapusher:39:in `new'
    from /Users/prathamesh/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/instapusher-0.1.9/bin/instapusher:39:in `<top (required)>'
    from /Users/prathamesh/.rbenv/versions/2.2.2/bin/instapusher:23:in `load'
    from /Users/prathamesh/.rbenv/versions/2.2.2/bin/instapusher:23:in `<main>'
```

**Comment by prathamesh-sonpatki** [comment]
Uninstalling `psych` gem fixed this issue.
